# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvFJpUzz-P5B-I2vvx4GmRLxIkCE67ri
"""

!pip install python-whois

!pip install requests beautifulsoup4 python-whois

import requests
from bs4 import BeautifulSoup
import re
import whois
from datetime import datetime

def analyze_website(url):
    results = []
    score = 0

    # Normalize URL
    if not url.startswith("http"):
        url = "https://" + url

    domain = url.replace("https://", "").replace("http://", "").split("/")[0]

    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text().lower()

        # ---------------------------
        # A. WEBSITE ELEMENT EXTRACTION
        # ---------------------------
        emails = re.findall(r"[\w\.-]+@[\w\.-]+", text)
        phones = re.findall(r"\+?\d[\d\s\-]{8,}", text)
        links = soup.find_all("a", href=True)

        suspicious_keywords = ["guaranteed profit", "100% return", "risk free", "double your money"]

        # ---------------------------
        # B. RULE-BASED DETECTION
        # ---------------------------

        # 1. Suspicious Claims
        for word in suspicious_keywords:
            if word in text:
                results.append({
                    "Detected Element": "Suspicious Claim",
                    "Matched External Evidence": "Keyword found on website",
                    "Rule Triggered": "Unrealistic promise",
                    "Risk Category": "Fraud Risk",
                    "Severity": "High",
                    "Rationale": f"Keyword '{word}' detected"
                })
                score += 30

        # 2. Missing Contact Info
        if not emails and not phones:
            results.append({
                "Detected Element": "Contact Information",
                "Matched External Evidence": "No email/phone found",
                "Rule Triggered": "Missing contact details",
                "Risk Category": "Transparency Risk",
                "Severity": "Medium",
                "Rationale": "No contact information available"
            })
            score += 15

        # 3. HTTPS Check
        if not url.startswith("https"):
            results.append({
                "Detected Element": "Website Security",
                "Matched External Evidence": "No HTTPS",
                "Rule Triggered": "Insecure connection",
                "Risk Category": "Security Risk",
                "Severity": "High",
                "Rationale": "Website not using HTTPS"
            })
            score += 30

        # 4. Privacy Policy
        if "privacy policy" not in text:
            results.append({
                "Detected Element": "Privacy Policy",
                "Matched External Evidence": "Not found on site",
                "Rule Triggered": "Missing policy",
                "Risk Category": "Compliance Risk",
                "Severity": "Medium",
                "Rationale": "Privacy policy not available"
            })
            score += 15

        # ---------------------------
        # C. EXTERNAL CORRELATION
        # ---------------------------

        # WHOIS - Domain Age
        try:
            domain_info = whois.whois(domain)
            creation_date = domain_info.creation_date

            if isinstance(creation_date, list):
                creation_date = creation_date[0]

            age_days = (datetime.now() - creation_date).days

            if age_days < 180:
                results.append({
                    "Detected Element": "Domain Age",
                    "Matched External Evidence": f"{age_days} days old",
                    "Rule Triggered": "New domain",
                    "Risk Category": "Reputation Risk",
                    "Severity": "High",
                    "Rationale": "Recently created domains are risky"
                })
                score += 25

        except:
            results.append({
                "Detected Element": "Domain Info",
                "Matched External Evidence": "WHOIS lookup failed",
                "Rule Triggered": "Unable to verify",
                "Risk Category": "Unknown Risk",
                "Severity": "Low",
                "Rationale": "Domain data not available"
            })

        # Google Search Presence
        try:
            search_url = f"https://www.google.com/search?q={domain}"
            search_res = requests.get(search_url, headers={"User-Agent": "Mozilla/5.0"})

            if "did not match any documents" in search_res.text.lower():
                results.append({
                    "Detected Element": "Online Presence",
                    "Matched External Evidence": "No search results",
                    "Rule Triggered": "No digital footprint",
                    "Risk Category": "Reputation Risk",
                    "Severity": "Medium",
                    "Rationale": "Website not found on search engines"
                })
                score += 15

        except:
            pass

        # ---------------------------
        # D. FINAL RISK OUTPUT
        # ---------------------------
        if score >= 60:
            overall = "High"
        elif score >= 30:
            overall = "Medium"
        else:
            overall = "Low"

        return {
            "Detailed Findings": results,
            "Overall Risk Score": score,
            "Overall Merchant Risk Rating": overall
        }

    except Exception as e:
        return {"Error": str(e)}


# ---------------------------
# RUN
# ---------------------------
url = input("Enter website URL: ")
output = analyze_website(url)

print("\n===== RISK ANALYSIS REPORT =====\n")

for item in output.get("Detailed Findings", []):
    print("Detected Element:", item["Detected Element"])
    print("Matched External Evidence:", item["Matched External Evidence"])
    print("Rule Triggered:", item["Rule Triggered"])
    print("Risk Category:", item["Risk Category"])
    print("Severity:", item["Severity"])
    print("Rationale:", item["Rationale"])
    print("-" * 50)

print("\nOverall Risk Score:", output.get("Overall Risk Score"))
print("Overall Merchant Risk Rating:", output.get("Overall Merchant Risk Rating"))

